version: '3'
services:
  mysql:
    container_name: lab1-iot-device-networking-mysql
    restart: always
    # command: --default-authentication-plugin=mysql_native_password
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root # TODO: Change this
      MYSQL_USER: user1
      MYSQL_PASSWORD: pass
      # MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - "3306:3306"

